### ISSUE TITLE
consistent git checkout for PR's and triggered pushes on branch

### ISSUE THREAD

**Issue by Krande** [ActionTestingX/action-toolbox#3]
As we have discussed in the past relying on "pull_request_target" will by default checkout the target branch. 

However, to enable the workflow's that are supposed to do verification on the incoming PR branch, we can simply change the checkout to use `${{ github.event.pull_request.head.sha }}` like so:

```yaml
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
```

However, we will need to test this on a simple dispatch trigger to see what it does when it is being called from a simple push to branch?

**Comment by VegarRingdalAibel** [comment]
Maybe we need a action to return correct ref ?

Atm we have these
- pull request
- dispatch on branch
- dispatch on tag
- push *accepted PR
- on new tag 

did I forget any?

**Comment by VegarRingdalAibel** [comment]
did a dump here of github env


https://github.com/ActionTestingX/dumpdebug/actions

**Comment by Krande** [comment]
I made a simple test in the dumpdebug repo. After that I had a talk with chatgpt on the subject :)

It might seem like running the following might be worth considering when we want the behavior to be defined in callable workflows ("tools") that can either be used for checkouts of the Incoming branch in a PR and also work as expected when running in a dispatch checking out the current branch outside a PR:

```yaml
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
``` 

Here is the conversation with chatgpt :)

I want to generalize my PR review algorithm using github actions,

Here is my example workflow for a tool that reviews an Incoming PR that is triggered using the "pull_request_target". 

```yaml
on:
  workflow_call:

# Add a small change here.

jobs:
  checkout_print_default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # This will NOT be able to read the changes from incoming PRs.
      - name: read a file and print it
        run: |
          cat .github/workflows/tool-checkout-print.yaml

  checkout_print_pr_head_sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # This WILL be able to read the changes from incoming PRs.
      - name: read a file and print it
        run: |
          cat .github/workflows/tool-checkout-print.yaml

  checkout_print_github_ref:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      # This will NOT be able to read the changes from incoming PRs.
      - name: read a file and print it
        run: |
          cat .github/workflows/tool-checkout-print.yaml
```
As mentioned in the comments I've added only the ref "${{ github.event.pull_request.head.sha }}" will be able to checkout the contents of the incoming branch in a PR. 

However, I want this tool to also work as expected when triggered from the main branch. Will "${{ github.event.pull_request.head.sha }}" work fine when this is triggered from outside a PR?

No, using `${{ github.event.pull_request.head.sha }}` will not work as expected when the workflow is triggered from the main branch or outside a pull request context. This variable specifically references the commit SHA of the head branch in a pull request event. When the workflow is triggered outside of a pull request, like a push to the main branch, this variable won't have a value, which could lead to errors or unexpected behavior in your workflow.

To make your GitHub Action workflow more general and handle both PRs and non-PR events, you can use a conditional check to determine the context and set the `ref` accordingly. For example:

```yaml
jobs:
  checkout_and_print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: read a file and print it
        run: |
          cat .github/workflows/tool-checkout-print.yaml
```

In this configuration:

- If the workflow is triggered by a pull request, `${{ github.event.pull_request.head.sha }}` will be used as the `ref`, checking out the head branch of the PR.
- If the workflow is triggered by a non-PR event (like a push to the main branch), `${{ github.ref }}` will be used as the `ref`, checking out the appropriate branch or tag associated with the event.

This approach ensures your GitHub Action workflow functions correctly regardless of whether it's triggered by a pull request or a direct push to a branch.
